/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem5;
  GtkWidget *menu5;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem6;
  GtkWidget *menu6;
  GtkWidget *menuitem7;
  GtkWidget *menu7;
  GtkWidget *about1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *newbutton1;
  GtkWidget *savebutton1;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton4;
  GtkWidget *toolitem1;
  GtkWidget *toolbutton3;
  GtkWidget *hbox1;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview1;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview1;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 800, 600);
  gtk_window_set_title (GTK_WINDOW (window2), _("R.I.G.O."));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window2), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu4), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu4), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu4), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu4), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu4), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu4), quit1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menu5 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menu5);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu5), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu5), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu5), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu5), delete1);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menu6 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menu6);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menu7 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menu7);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu7), about1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  newbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_show (newbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), newbutton1);

  savebutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_show (savebutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), savebutton1);

  tmp_image = gtk_image_new_from_stock ("gtk-directory", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton4 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Section"));
  gtk_widget_show (toolbutton4);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton4);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  tmp_image = gtk_image_new_from_stock ("gtk-yes", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton3 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Export"));
  gtk_widget_show (toolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton3);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview1);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview1);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window2, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window2, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window2, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (window2, new1, "new1");
  GLADE_HOOKUP_OBJECT (window2, open1, "open1");
  GLADE_HOOKUP_OBJECT (window2, save1, "save1");
  GLADE_HOOKUP_OBJECT (window2, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (window2, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (window2, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window2, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (window2, menu5, "menu5");
  GLADE_HOOKUP_OBJECT (window2, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (window2, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (window2, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (window2, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (window2, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (window2, menu6, "menu6");
  GLADE_HOOKUP_OBJECT (window2, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (window2, menu7, "menu7");
  GLADE_HOOKUP_OBJECT (window2, about1, "about1");
  GLADE_HOOKUP_OBJECT (window2, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window2, newbutton1, "newbutton1");
  GLADE_HOOKUP_OBJECT (window2, savebutton1, "savebutton1");
  GLADE_HOOKUP_OBJECT (window2, toolbutton4, "toolbutton4");
  GLADE_HOOKUP_OBJECT (window2, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (window2, toolbutton3, "toolbutton3");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window2, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, statusbar1, "statusbar1");

  gtk_window_add_accel_group (GTK_WINDOW (window2), accel_group);

  return window2;
}

GtkWidget*
create_menu8 (void)
{
  GtkWidget *menu8;
  GtkWidget *add_to_last1;
  GtkWidget *image3;
  GtkWidget *new_section1;
  GtkWidget *image4;
  GtkWidget *separator1;
  GtkWidget *save_project1;
  GtkWidget *export1;
  GtkWidget *export1_menu;
  GtkWidget *text1;
  GtkWidget *truth_format1;
  GtkWidget *latex1;
  GtkWidget *html2;

  menu8 = gtk_menu_new ();

  add_to_last1 = gtk_image_menu_item_new_with_mnemonic (_("Add to Last"));
  gtk_widget_show (add_to_last1);
  gtk_container_add (GTK_CONTAINER (menu8), add_to_last1);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image3);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_to_last1), image3);

  new_section1 = gtk_image_menu_item_new_with_mnemonic (_("New Section"));
  gtk_widget_show (new_section1);
  gtk_container_add (GTK_CONTAINER (menu8), new_section1);

  image4 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image4);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_section1), image4);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menu8), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  save_project1 = gtk_menu_item_new_with_mnemonic (_("Save Project"));
  gtk_widget_show (save_project1);
  gtk_container_add (GTK_CONTAINER (menu8), save_project1);

  export1 = gtk_menu_item_new_with_mnemonic (_("Export"));
  gtk_widget_show (export1);
  gtk_container_add (GTK_CONTAINER (menu8), export1);

  export1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (export1), export1_menu);

  text1 = gtk_menu_item_new_with_mnemonic (_("Text"));
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (export1_menu), text1);

  truth_format1 = gtk_menu_item_new_with_mnemonic (_("Truth Format"));
  gtk_widget_show (truth_format1);
  gtk_container_add (GTK_CONTAINER (export1_menu), truth_format1);

  latex1 = gtk_menu_item_new_with_mnemonic (_("Latex"));
  gtk_widget_show (latex1);
  gtk_container_add (GTK_CONTAINER (export1_menu), latex1);

  html2 = gtk_menu_item_new_with_mnemonic (_("HTML"));
  gtk_widget_show (html2);
  gtk_container_add (GTK_CONTAINER (export1_menu), html2);

  g_signal_connect ((gpointer) add_to_last1, "activate",
                    G_CALLBACK (on_add_to_last1_activate),
                    NULL);
  g_signal_connect ((gpointer) new_section1, "activate",
                    G_CALLBACK (on_new_section1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_project1, "activate",
                    G_CALLBACK (on_save_project1_activate),
                    NULL);
  g_signal_connect ((gpointer) export1, "activate",
                    G_CALLBACK (on_export1_activate),
                    NULL);
  g_signal_connect ((gpointer) text1, "activate",
                    G_CALLBACK (on_text1_activate),
                    NULL);
  g_signal_connect ((gpointer) truth_format1, "activate",
                    G_CALLBACK (on_truth_format1_activate),
                    NULL);
  g_signal_connect ((gpointer) latex1, "activate",
                    G_CALLBACK (on_latex1_activate),
                    NULL);
  g_signal_connect ((gpointer) html2, "activate",
                    G_CALLBACK (on_html2_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu8, menu8, "menu8");
  GLADE_HOOKUP_OBJECT (menu8, add_to_last1, "add_to_last1");
  GLADE_HOOKUP_OBJECT (menu8, image3, "image3");
  GLADE_HOOKUP_OBJECT (menu8, new_section1, "new_section1");
  GLADE_HOOKUP_OBJECT (menu8, image4, "image4");
  GLADE_HOOKUP_OBJECT (menu8, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (menu8, save_project1, "save_project1");
  GLADE_HOOKUP_OBJECT (menu8, export1, "export1");
  GLADE_HOOKUP_OBJECT (menu8, export1_menu, "export1_menu");
  GLADE_HOOKUP_OBJECT (menu8, text1, "text1");
  GLADE_HOOKUP_OBJECT (menu8, truth_format1, "truth_format1");
  GLADE_HOOKUP_OBJECT (menu8, latex1, "latex1");
  GLADE_HOOKUP_OBJECT (menu8, html2, "html2");

  return menu8;
}

