/////////////////////////////////////////////////////////////////////////////
// Name:        mainFrame.cpp
// Purpose:     
// Author:      Jeremy Wright
// Modified by: 
// Created:     Thu 16 Feb 2006 08:09:44 PM PST
// RCS-ID:      
// Copyright:   GPL v2
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 16 Feb 2006 08:09:44 PM PST

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "mainFrame.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "mainFrame.h"

////@begin XPM images
////@end XPM images

/*!
 * mainFrame type definition
 */

IMPLEMENT_DYNAMIC_CLASS( mainFrame, wxDialog )

/*!
 * mainFrame event table definition
 */

BEGIN_EVENT_TABLE( mainFrame, wxDialog )

////@begin mainFrame event table entries
////@end mainFrame event table entries

END_EVENT_TABLE()

/*!
 * mainFrame constructors
 */

mainFrame::mainFrame( )
{
}

mainFrame::mainFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create(parent, id, caption, pos, size, style);
}

/*!
 * mainFrame creator
 */

bool mainFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin mainFrame member initialisation
////@end mainFrame member initialisation

////@begin mainFrame creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end mainFrame creation
    return TRUE;
}

/*!
 * Control creation for mainFrame
 */

void mainFrame::CreateControls()
{    
////@begin mainFrame content construction
    // Generated by DialogBlocks, Thu 16 Feb 2006 08:10:58 PM PST (Personal Edition)

    mainFrame* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxHtmlWindow* itemHtmlWindow3 = new wxHtmlWindow( itemDialog1, ID_HTMLWINDOW, wxDefaultPosition, wxSize(200, 150), wxHW_SCROLLBAR_AUTO|wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );

////@end mainFrame content construction
}

/*!
 * Should we show tooltips?
 */

bool mainFrame::ShowToolTips()
{
    return TRUE;
}

/*!
 * Get bitmap resources
 */

wxBitmap mainFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin mainFrame bitmap retrieval
    return wxNullBitmap;
////@end mainFrame bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon mainFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin mainFrame icon retrieval
    return wxNullIcon;
////@end mainFrame icon retrieval
}
