/////////////////////////////////////////////////////////////////////////////
// Name:        mainFrame.h
// Purpose:     
// Author:      Jeremy Wright
// Modified by: 
// Created:     Thu 16 Feb 2006 08:09:44 PM PST
// RCS-ID:      
// Copyright:   GPL v2
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 16 Feb 2006 08:09:44 PM PST

#ifndef _MAINFRAME_H_
#define _MAINFRAME_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "mainFrame.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/html/htmlwin.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define SYMBOL_MAINFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_MAINFRAME_TITLE _(".::Rigo::.")
#define SYMBOL_MAINFRAME_IDNAME ID_DIALOG
#define SYMBOL_MAINFRAME_SIZE wxSize(400, 300)
#define SYMBOL_MAINFRAME_POSITION wxDefaultPosition
#define ID_HTMLWINDOW 10001
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * mainFrame class declaration
 */

class mainFrame: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( mainFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    mainFrame( );
    mainFrame( wxWindow* parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString& caption = SYMBOL_MAINFRAME_TITLE, const wxPoint& pos = SYMBOL_MAINFRAME_POSITION, const wxSize& size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString& caption = SYMBOL_MAINFRAME_TITLE, const wxPoint& pos = SYMBOL_MAINFRAME_POSITION, const wxSize& size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin mainFrame event handler declarations

////@end mainFrame event handler declarations

////@begin mainFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end mainFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin mainFrame member variables
////@end mainFrame member variables
};

#endif
    // _MAINFRAME_H_
